# Generated by Django 4.2.4 on 2023-08-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_created_at_alter_ads_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={},
        ),
        migrations.RemoveField(
            model_name='ads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category')),
            ],
        ),
    ]
