# Generated by Django 4.2.4 on 2023-08-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0004_category_alter_ads_options_remove_ads_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AddField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ads',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ads',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ads',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.subcategory'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('I want to learn', 'I want to learn'), ('I can teach', 'I can teach')], default='I want to learn', max_length=100),
        ),
        migrations.AddField(
            model_name='ads',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
