# Generated by Django 4.2.4 on 2023-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_options_ads_created_at_ads_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(default='images.jpg', upload_to='images/ads/'),
        ),
    ]
